# Generated by Django 5.0.4 on 2024-04-21 19:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genQuiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='options',
            new_name='option1',
        ),
        migrations.AddField(
            model_name='quiz',
            name='option2',
            field=models.TextField(default=datetime.datetime(2024, 4, 21, 19, 2, 30, 542427, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='option3',
            field=models.TextField(blank=True),
        ),
    ]
